languageCode = "en-us"
title = "OHSHIMA LAB"
baseURL = "http://localhost:1313/"
theme = "massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
[params.posts]
    folderName = "post"
    pageSize = "6"
    featuredPost = true
    paginationPages = 2
    showFirstLast = false
[menu]
  [[menu.main]]
  Name = "About"
  URL = "/about"

  [[menu.main]]
  Name = "Members"
  URL = "/members"

  [[menu.main]]
  Name = "Admission"
  URL = "/admission"

[languages]
[languages.en]
  languageName = "English"
# [languages.es]
#   languageName = "Español"
#   title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
